from pathlib import Path
from settings.constants import DATA_DIR_NAME, DATA_FILE_NAME, LOGS_DIR_NAME, JSON_FILE_NAME

BASE_PROJECT_DIR = Path(__file__).resolve().parent.parent.parent

DATA_DIR_PATH = BASE_PROJECT_DIR / DATA_DIR_NAME
DATA_FILE_PATH = BASE_PROJECT_DIR / DATA_DIR_NAME / DATA_FILE_NAME

LOGS_DIR_PATH = BASE_PROJECT_DIR / "logs" / LOGS_DIR_NAME

JSON_DIR_PATH = BASE_PROJECT_DIR / DATA_DIR_NAME / JSON_FILE_NAME